###
# Direct Get
GET http://localhost:9091/persons/1

###
# Direct Update
PUT http://localhost:9091/persons/1
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Doe",
  "birthday": "1967-04-05"
}

###
# LoginUser1
POST http://gateway:password@localhost:9080/oauth/token 
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=user1&password=password

> {% client.global.set("access_token_user1", response.body.access_token); %}

###
# LoginUser2
POST http://gateway:password@localhost:9080/oauth/token 
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=user2&password=password

> {% client.global.set("access_token_user2", response.body.access_token); %}

###
# LoginAdmin
POST http://gateway:password@localhost:9080/oauth/token 
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=admin&password=password

> {% client.global.set("access_token_admin", response.body.access_token); %}

###
# Get Via Coded Gateway
GET http://localhost:9081/personservice/persons/1
Authorization: Bearer {{access_token_user1}}

###
# Update Via Coded Gateway
PUT http://localhost:9081/personservice/persons/1
Content-Type: application/json
Authorization: Bearer {{access_token_user1}}

{
  "firstname": "John",
  "lastname": "Jacobsen",
  "birthday": "1967-04-01"
}

###
# Get Order Via Coded Gateway
GET http://localhost:9081/orderservice/orders/1
Authorization: Bearer {{access_token_user1}}

###
# Get Order Via Coded Gateway
GET http://localhost:9081/orderservice/orders/1
Authorization: Bearer {{access_token_user2}}


###
# Get Person Via Spring Cloud Gateway
GET http://localhost:9081/personservice/persons/1

###
# Update Via Spring Cloud Gateway
PUT http://localhost:9081/personservice/persons/1
Content-Type: application/json

{
  "firstname": "John",
  "lastname": "Jacobsen",
  "birthday": "1967-04-01"
}

###
# Get Order Via Spring Cloud Gateway
GET http://localhost:9081/orderservice/orders/1
X-API-KEY: 123

###
