server:
  port: 9081
  error:
    include-stacktrace: never


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # To run the application, replace this with a valid JWK Set URI
          jwk-set-uri: http://localhost:9080/.well-known/jwks.json